### ISSUE TITLE
Registration/Sign up Page

### ISSUE THREAD

**Issue by jcarn760** [jcarn760/veterans-health#15]
We want to add a registration/sign up page that has a large form that asks a user to fill out in order to register for an account.

Some ideas for form data inputs are:
-Username
-Password (ensure it adheres to the secure password standard ie. minimum 8 characters long, at least 1 lowercase, 1 uppercase, 1 number, and 1 character are included in the password).
- First Name
- Last Name
- email
- fitness goal (a method that we can store this and attach it to the status bar on the home page something such as weight goal or a certain number of days to workout goal)
- DOB
- Height
- weight
- gender

and then handle this form data accordingly.

we will want to make sure to have responses to an unsecure password attempt and whether or not the registration was successful or not and if it did fail, why.

**Comment by Sky-De** [comment]
@jcarn760 do you have any design for this?
Inform me about that and provide some information related to that
Then please assign this to me
Thanks
